name: "create release with assets"
on:
  push:
    # Run for tagged commits, the tag name should be X.Y.Z to be used as version in pom.xml
    tags:
      - '[1-9]*'
jobs:
  publish:
    name: "release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "check out code"
        uses: actions/checkout@v4

      - name: "set up JDK"
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'maven'

      - name: "set version from tag in all pom.xml to $GITHUB_REF_NAME"
        run: "mvn versions:set -DnewVersion=$GITHUB_REF_NAME ; mvn versions:commit"

      - name: "compile and build package"
        run: mvn -B clean install

      - name: "create release and upload assets"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "chat-server/target/chat_service.jar,chat-client-java-lib/target/chat-client-java-lib.jar"
