name: "test build"
on: [ push, pull_request ]
jobs:
  test:
    name: "JDK ${{ matrix.java }} build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    steps:

      - name: "check out code"
        uses: actions/checkout@v4

      - name: "set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: "build and test with Maven"
        run: mvn -B clean install

