name: "test build"
on: [ push, pull_request ]
jobs:
  test:
    name: "JDK ${{ matrix.java }} build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:

      - name: "check out code"
        uses: actions/checkout@v3

      - name: "set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}

      - name: "restore cached maven repository"
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-jdk${{ matrix.java }}-

      - name: "build and test with Maven"
        run: mvn -B clean test

